[2025-04-22T18:49:00.641+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T18:49:00.668+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Upload_to_HDFS manual__2025-04-22T18:47:34.001313+00:00 [queued]>
[2025-04-22T18:49:00.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.Upload_to_HDFS manual__2025-04-22T18:47:34.001313+00:00 [queued]>
[2025-04-22T18:49:00.674+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-22T18:49:00.689+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): Upload_to_HDFS> on 2025-04-22 18:47:34.001313+00:00
[2025-04-22T18:49:00.695+0000] {standard_task_runner.py:63} INFO - Started process 675 to run task
[2025-04-22T18:49:00.697+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'Upload_to_HDFS', 'manual__2025-04-22T18:47:34.001313+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmpizf71rn5']
[2025-04-22T18:49:00.698+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask Upload_to_HDFS
[2025-04-22T18:49:00.725+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.Upload_to_HDFS manual__2025-04-22T18:47:34.001313+00:00 [running]> on host 6df7355a8d19
[2025-04-22T18:49:00.762+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'Upload_to_HDFS', field 'bash_command'. Template: 'bash /opt/airflow/Scripts/upload_to_hdfs.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/Scripts/upload_to_hdfs.sh
[2025-04-22T18:49:00.764+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash /opt/airflow/Scripts/upload_to_hdfs.sh
[2025-04-22T18:49:00.768+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=Upload_to_HDFS, run_id=manual__2025-04-22T18:47:34.001313+00:00, execution_date=20250422T184734, start_date=20250422T184900, end_date=20250422T184900
[2025-04-22T18:49:00.777+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 94 for task Upload_to_HDFS (bash /opt/airflow/Scripts/upload_to_hdfs.sh; 675)
[2025-04-22T18:49:00.789+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-22T18:49:00.801+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T18:49:00.802+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
