[2025-04-24T18:43:58.509+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-24T18:43:58.533+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [queued]>
[2025-04-24T18:43:58.538+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [queued]>
[2025-04-24T18:43:58.539+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-04-24T18:43:58.552+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_test> on 2025-04-24 18:30:00+00:00
[2025-04-24T18:43:58.557+0000] {standard_task_runner.py:63} INFO - Started process 142 to run task
[2025-04-24T18:43:58.560+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'run_spark_test', 'scheduled__2025-04-24T18:30:00+00:00', '--job-id', '287', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpjrv0tknf']
[2025-04-24T18:43:58.562+0000] {standard_task_runner.py:91} INFO - Job 287: Subtask run_spark_test
[2025-04-24T18:43:58.595+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [running]> on host 6555ac884751
[2025-04-24T18:43:58.649+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T18:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-24T18:30:00+00:00'
[2025-04-24T18:43:58.650+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-24T18:43:58.660+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T18:43:58.661+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/spark-apps/test.py']
[2025-04-24T18:43:58.671+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T18:44:01.125+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2025-04-24T18:44:01.125+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2025-04-24T18:44:01.276+0000] {subprocess.py:93} INFO - 25/04/24 18:44:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-24T18:44:02.545+0000] {subprocess.py:93} INFO - 25/04/24 18:44:02 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master localhost:7077
[2025-04-24T18:44:02.546+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-24T18:44:02.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-04-24T18:44:02.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-04-24T18:44:02.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-24T18:44:02.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2025-04-24T18:44:02.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2025-04-24T18:44:02.546+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2025-04-24T18:44:02.546+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:7077
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2025-04-24T18:44:02.547+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - 	... 4 more
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7077
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2025-04-24T18:44:02.548+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2025-04-24T18:44:02.549+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2025-04-24T18:44:02.549+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2025-04-24T18:44:02.549+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2025-04-24T18:44:02.549+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2025-04-24T18:44:02.549+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2025-04-24T18:44:02.549+0000] {subprocess.py:93} INFO - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2025-04-24T18:44:02.549+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2025-04-24T18:44:02.549+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-24T18:44:22.504+0000] {subprocess.py:93} INFO - 25/04/24 18:44:22 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master localhost:7077
[2025-04-24T18:44:22.505+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-24T18:44:22.505+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-04-24T18:44:22.505+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-04-24T18:44:22.505+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-24T18:44:22.506+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2025-04-24T18:44:22.506+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2025-04-24T18:44:22.506+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2025-04-24T18:44:22.506+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2025-04-24T18:44:22.506+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2025-04-24T18:44:22.506+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-04-24T18:44:22.507+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-04-24T18:44:22.507+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-24T18:44:22.507+0000] {subprocess.py:93} INFO - Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:7077
[2025-04-24T18:44:22.507+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2025-04-24T18:44:22.507+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2025-04-24T18:44:22.508+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2025-04-24T18:44:22.508+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2025-04-24T18:44:22.508+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2025-04-24T18:44:22.508+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2025-04-24T18:44:22.508+0000] {subprocess.py:93} INFO - 	... 4 more
[2025-04-24T18:44:22.508+0000] {subprocess.py:93} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7077
[2025-04-24T18:44:22.509+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-04-24T18:44:22.509+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-04-24T18:44:22.509+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-04-24T18:44:22.509+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-04-24T18:44:22.509+0000] {subprocess.py:93} INFO - 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2025-04-24T18:44:22.509+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2025-04-24T18:44:22.509+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2025-04-24T18:44:22.509+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2025-04-24T18:44:22.510+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2025-04-24T18:44:22.510+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2025-04-24T18:44:22.510+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2025-04-24T18:44:22.510+0000] {subprocess.py:93} INFO - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2025-04-24T18:44:22.510+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2025-04-24T18:44:22.510+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-24T18:44:42.505+0000] {subprocess.py:93} INFO - 25/04/24 18:44:42 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master localhost:7077
[2025-04-24T18:44:42.505+0000] {subprocess.py:93} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2025-04-24T18:44:42.505+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2025-04-24T18:44:42.506+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2025-04-24T18:44:42.506+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2025-04-24T18:44:42.506+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2025-04-24T18:44:42.506+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2025-04-24T18:44:42.506+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2025-04-24T18:44:42.506+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2025-04-24T18:44:42.506+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2025-04-24T18:44:42.506+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:7077
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - 	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2025-04-24T18:44:42.507+0000] {subprocess.py:93} INFO - 	at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - 	... 4 more
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7077
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2025-04-24T18:44:42.508+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2025-04-24T18:44:42.509+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2025-04-24T18:44:42.509+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2025-04-24T18:44:42.509+0000] {subprocess.py:93} INFO - 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2025-04-24T18:44:42.509+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2025-04-24T18:44:42.509+0000] {subprocess.py:93} INFO - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2025-04-24T18:44:42.509+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2025-04-24T18:44:42.509+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-24T18:45:02.501+0000] {subprocess.py:93} INFO - 25/04/24 18:45:02 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2025-04-24T18:45:02.502+0000] {subprocess.py:93} INFO - 25/04/24 18:45:02 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2025-04-24T18:45:02.987+0000] {subprocess.py:93} INFO - 25/04/24 18:45:02 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2025-04-24T18:45:04.014+0000] {subprocess.py:93} INFO - Connected to Spark Master: spark://localhost:7077
[2025-04-24T18:45:04.014+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-24T18:45:04.014+0000] {subprocess.py:93} INFO -   File "/opt/spark-apps/test.py", line 13, in <module>
[2025-04-24T18:45:04.014+0000] {subprocess.py:93} INFO -     df = spark.range(1, 6)
[2025-04-24T18:45:04.015+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^
[2025-04-24T18:45:04.015+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 926, in range
[2025-04-24T18:45:04.015+0000] {subprocess.py:93} INFO -     jdf = self._jsparkSession.range(int(start), int(end), int(step), int(numPartitions))
[2025-04-24T18:45:04.015+0000] {subprocess.py:93} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T18:45:04.015+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2025-04-24T18:45:04.015+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-04-24T18:45:04.015+0000] {subprocess.py:93} INFO -                    ^^^^^^^^^^^^^^^^^
[2025-04-24T18:45:04.015+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-04-24T18:45:04.016+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-04-24T18:45:04.016+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^
[2025-04-24T18:45:04.016+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/py4j/protocol.py", line 326, in get_return_value
[2025-04-24T18:45:04.016+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-04-24T18:45:04.017+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o25.range.
[2025-04-24T18:45:04.017+0000] {subprocess.py:93} INFO - : java.lang.IllegalStateException: LiveListenerBus is stopped.
[2025-04-24T18:45:04.017+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.LiveListenerBus.addToQueue(LiveListenerBus.scala:92)
[2025-04-24T18:45:04.017+0000] {subprocess.py:93} INFO - 	at org.apache.spark.scheduler.LiveListenerBus.addToStatusQueue(LiveListenerBus.scala:75)
[2025-04-24T18:45:04.017+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.internal.SharedState.<init>(SharedState.scala:115)
[2025-04-24T18:45:04.017+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.$anonfun$sharedState$1(SparkSession.scala:143)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.sharedState$lzycompute(SparkSession.scala:143)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.sharedState(SparkSession.scala:142)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:162)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:160)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:157)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:212)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.SparkSession.range(SparkSession.scala:556)
[2025-04-24T18:45:04.018+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-24T18:45:04.019+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-24T18:45:04.020+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-24T18:45:04.020+0000] {subprocess.py:93} INFO - 
[2025-04-24T18:45:04.428+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T18:45:04.429+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-24T18:45:04.436+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T18:45:04.441+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=run_spark_test, run_id=scheduled__2025-04-24T18:30:00+00:00, execution_date=20250424T183000, start_date=20250424T184358, end_date=20250424T184504
[2025-04-24T18:45:04.461+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 287 for task run_spark_test (Bash command failed. The command returned a non-zero exit code 1.; 142)
[2025-04-24T18:45:04.500+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-24T18:45:04.509+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T18:45:04.509+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
