[2025-04-24T18:45:36.651+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-24T18:45:36.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [queued]>
[2025-04-24T18:45:36.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [queued]>
[2025-04-24T18:45:36.680+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2025-04-24T18:45:36.691+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_test> on 2025-04-24 18:30:00+00:00
[2025-04-24T18:45:36.697+0000] {standard_task_runner.py:63} INFO - Started process 344 to run task
[2025-04-24T18:45:36.699+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'run_spark_test', 'scheduled__2025-04-24T18:30:00+00:00', '--job-id', '288', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpa8dkxj3z']
[2025-04-24T18:45:36.700+0000] {standard_task_runner.py:91} INFO - Job 288: Subtask run_spark_test
[2025-04-24T18:45:36.730+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-24T18:30:00+00:00 [running]> on host 6555ac884751
[2025-04-24T18:45:36.785+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T18:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-24T18:30:00+00:00'
[2025-04-24T18:45:36.785+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-24T18:45:36.796+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-24T18:45:36.797+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/spark-apps/test.py']
[2025-04-24T18:45:36.809+0000] {subprocess.py:86} INFO - Output:
[2025-04-24T18:45:38.976+0000] {subprocess.py:93} INFO - Exception in thread "main" org.apache.spark.SparkException: Master must either be yarn or start with spark, mesos, k8s, or local
[2025-04-24T18:45:38.976+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:1052)
[2025-04-24T18:45:38.976+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:261)
[2025-04-24T18:45:38.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:969)
[2025-04-24T18:45:38.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:199)
[2025-04-24T18:45:38.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:222)
[2025-04-24T18:45:38.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-04-24T18:45:38.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-04-24T18:45:38.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-04-24T18:45:38.977+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-04-24T18:45:39.026+0000] {subprocess.py:93} INFO - Failed to connect to Spark Master: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-04-24T18:45:39.027+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-24T18:45:39.027+0000] {subprocess.py:93} INFO -   File "/opt/spark-apps/test.py", line 7, in <module>
[2025-04-24T18:45:39.027+0000] {subprocess.py:93} INFO -     .getOrCreate()
[2025-04-24T18:45:39.027+0000] {subprocess.py:93} INFO -      ^^^^^^^^^^^^^
[2025-04-24T18:45:39.028+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
[2025-04-24T18:45:39.028+0000] {subprocess.py:93} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-04-24T18:45:39.028+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T18:45:39.028+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 515, in getOrCreate
[2025-04-24T18:45:39.029+0000] {subprocess.py:93} INFO -     SparkContext(conf=conf or SparkConf())
[2025-04-24T18:45:39.029+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 201, in __init__
[2025-04-24T18:45:39.029+0000] {subprocess.py:93} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-04-24T18:45:39.029+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/context.py", line 436, in _ensure_initialized
[2025-04-24T18:45:39.029+0000] {subprocess.py:93} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-04-24T18:45:39.029+0000] {subprocess.py:93} INFO -                                        ^^^^^^^^^^^^^^^^^^^^
[2025-04-24T18:45:39.029+0000] {subprocess.py:93} INFO -   File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
[2025-04-24T18:45:39.030+0000] {subprocess.py:93} INFO -     raise PySparkRuntimeError(
[2025-04-24T18:45:39.030+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-04-24T18:45:39.095+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-24T18:45:39.096+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-24T18:45:39.101+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-24T18:45:39.104+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=run_spark_test, run_id=scheduled__2025-04-24T18:30:00+00:00, execution_date=20250424T183000, start_date=20250424T184536, end_date=20250424T184539
[2025-04-24T18:45:39.120+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 288 for task run_spark_test (Bash command failed. The command returned a non-zero exit code 1.; 344)
[2025-04-24T18:45:39.157+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-24T18:45:39.181+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-24T18:45:39.181+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
