[2025-04-22T22:04:12.032+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T22:04:12.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.upload_to_hdfs scheduled__2025-04-22T21:50:00+00:00 [queued]>
[2025-04-22T22:04:12.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.upload_to_hdfs scheduled__2025-04-22T21:50:00+00:00 [queued]>
[2025-04-22T22:04:12.073+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-22T22:04:12.089+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): upload_to_hdfs> on 2025-04-22 21:50:00+00:00
[2025-04-22T22:04:12.098+0000] {standard_task_runner.py:63} INFO - Started process 90 to run task
[2025-04-22T22:04:12.101+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'upload_to_hdfs', 'scheduled__2025-04-22T21:50:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmp815r3xw5']
[2025-04-22T22:04:12.103+0000] {standard_task_runner.py:91} INFO - Job 142: Subtask upload_to_hdfs
[2025-04-22T22:04:12.142+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.upload_to_hdfs scheduled__2025-04-22T21:50:00+00:00 [running]> on host eb39fe307f49
[2025-04-22T22:04:12.214+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T21:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T21:50:00+00:00'
[2025-04-22T22:04:12.215+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-22T22:04:12.232+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T22:04:12.233+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c " dfs -put -f /opt/airflow/includes/local\\ warehouse/bronze/stock-prices.jsonl hdfs://localhost:9000/bronze/"']
[2025-04-22T22:04:12.246+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T22:04:12.250+0000] {subprocess.py:93} INFO - bash: line 1: dfs: command not found
[2025-04-22T22:04:12.251+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-22T22:04:12.251+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-22T22:04:12.257+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-22T22:04:12.260+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=upload_to_hdfs, run_id=scheduled__2025-04-22T21:50:00+00:00, execution_date=20250422T215000, start_date=20250422T220412, end_date=20250422T220412
[2025-04-22T22:04:12.272+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 142 for task upload_to_hdfs (Bash command failed. The command returned a non-zero exit code 127.; 90)
[2025-04-22T22:04:12.315+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-22T22:04:12.325+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T22:04:12.326+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
