[2025-04-22T18:21:25.211+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T18:21:25.233+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.create_hdfs_dirs scheduled__2025-04-22T18:10:00+00:00 [queued]>
[2025-04-22T18:21:25.238+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.create_hdfs_dirs scheduled__2025-04-22T18:10:00+00:00 [queued]>
[2025-04-22T18:21:25.238+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-22T18:21:25.251+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): create_hdfs_dirs> on 2025-04-22 18:10:00+00:00
[2025-04-22T18:21:25.257+0000] {standard_task_runner.py:63} INFO - Started process 139 to run task
[2025-04-22T18:21:25.259+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'create_hdfs_dirs', 'scheduled__2025-04-22T18:10:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmpvojkxrmr']
[2025-04-22T18:21:25.260+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask create_hdfs_dirs
[2025-04-22T18:21:25.288+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.create_hdfs_dirs scheduled__2025-04-22T18:10:00+00:00 [running]> on host 6df7355a8d19
[2025-04-22T18:21:25.348+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='create_hdfs_dirs' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T18:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T18:10:00+00:00'
[2025-04-22T18:21:25.348+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-22T18:21:25.364+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T18:21:25.364+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'hdfs dfs -mkdir -p /bronze && hdfs dfs -mkdir -p /silver']
[2025-04-22T18:21:25.374+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T18:21:25.376+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: hdfs: command not found
[2025-04-22T18:21:25.377+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-22T18:21:25.378+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-22T18:21:25.383+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-22T18:21:25.387+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=create_hdfs_dirs, run_id=scheduled__2025-04-22T18:10:00+00:00, execution_date=20250422T181000, start_date=20250422T182125, end_date=20250422T182125
[2025-04-22T18:21:25.396+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 80 for task create_hdfs_dirs (Bash command failed. The command returned a non-zero exit code 127.; 139)
[2025-04-22T18:21:25.431+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-22T18:21:25.454+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T18:21:25.455+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
