[2025-04-22T12:59:00.754+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T12:59:00.786+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.produce_stock_data scheduled__2025-04-22T12:40:00+00:00 [queued]>
[2025-04-22T12:59:00.795+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.produce_stock_data scheduled__2025-04-22T12:40:00+00:00 [queued]>
[2025-04-22T12:59:00.796+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-22T12:59:00.813+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): produce_stock_data> on 2025-04-22 12:40:00+00:00
[2025-04-22T12:59:00.820+0000] {standard_task_runner.py:63} INFO - Started process 188 to run task
[2025-04-22T12:59:00.822+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'produce_stock_data', 'scheduled__2025-04-22T12:40:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmp__27djqr']
[2025-04-22T12:59:00.824+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask produce_stock_data
[2025-04-22T12:59:00.869+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.produce_stock_data scheduled__2025-04-22T12:40:00+00:00 [running]> on host 1705554292e6
[2025-04-22T12:59:00.950+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='produce_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T12:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T12:40:00+00:00'
[2025-04-22T12:59:00.951+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-22T12:59:00.971+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T12:59:00.971+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/airflow/Source/alpha_vantage_producer.py']
[2025-04-22T12:59:00.988+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T12:59:01.079+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/airflow/Source/alpha_vantage_producer.py': [Errno 2] No such file or directory
[2025-04-22T12:59:01.086+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-22T12:59:01.086+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-22T12:59:01.094+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-22T12:59:01.099+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_kafka_pipeline, task_id=produce_stock_data, run_id=scheduled__2025-04-22T12:40:00+00:00, execution_date=20250422T124000, start_date=20250422T125900, end_date=20250422T125901
[2025-04-22T12:59:01.110+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task produce_stock_data (Bash command failed. The command returned a non-zero exit code 2.; 188)
[2025-04-22T12:59:01.155+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-22T12:59:01.186+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T12:59:01.187+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
