[2025-04-23T18:13:19.538+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-23T18:13:19.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-23T17:50:00+00:00 [queued]>
[2025-04-23T18:13:19.582+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-23T17:50:00+00:00 [queued]>
[2025-04-23T18:13:19.583+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-23T18:13:19.596+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): run_spark_test> on 2025-04-23 17:50:00+00:00
[2025-04-23T18:13:19.601+0000] {standard_task_runner.py:63} INFO - Started process 137 to run task
[2025-04-23T18:13:19.604+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'run_spark_test', 'scheduled__2025-04-23T17:50:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmpg43ryrs6']
[2025-04-23T18:13:19.605+0000] {standard_task_runner.py:91} INFO - Job 179: Subtask run_spark_test
[2025-04-23T18:13:19.639+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.run_spark_test scheduled__2025-04-23T17:50:00+00:00 [running]> on host 5b95d4068e09
[2025-04-23T18:13:19.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='run_spark_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T17:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T17:50:00+00:00'
[2025-04-23T18:13:19.706+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-23T18:13:19.724+0000] {spark_submit.py:305} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-04-23T18:13:19.725+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --verbose /opt/spark-apps/test.py
[2025-04-23T18:13:19.844+0000] {spark_submit.py:644} INFO - /home/airflow/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-23T18:13:19.846+0000] {spark_submit.py:644} INFO - JAVA_HOME is not set
[2025-04-23T18:13:19.847+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-23T18:13:19.855+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose /opt/spark-apps/test.py. Error code is: 1.
[2025-04-23T18:13:19.859+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_kafka_pipeline, task_id=run_spark_test, run_id=scheduled__2025-04-23T17:50:00+00:00, execution_date=20250423T175000, start_date=20250423T181319, end_date=20250423T181319
[2025-04-23T18:13:20.050+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 179 for task run_spark_test (Cannot execute: spark-submit --master yarn --name arrow-spark --verbose /opt/spark-apps/test.py. Error code is: 1.; 137)
[2025-04-23T18:13:20.097+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-23T18:13:20.116+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T18:13:20.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
