[2025-04-22T20:09:04.178+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-22T20:09:04.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_kafka_pipeline.upload_to_hdfs scheduled__2025-04-22T19:50:00+00:00 [queued]>
[2025-04-22T20:09:04.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_kafka_pipeline.upload_to_hdfs scheduled__2025-04-22T19:50:00+00:00 [queued]>
[2025-04-22T20:09:04.207+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-22T20:09:04.219+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): upload_to_hdfs> on 2025-04-22 19:50:00+00:00
[2025-04-22T20:09:04.224+0000] {standard_task_runner.py:63} INFO - Started process 119 to run task
[2025-04-22T20:09:04.226+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'stock_kafka_pipeline', 'upload_to_hdfs', 'scheduled__2025-04-22T19:50:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/stock_kafka_pipeline.py', '--cfg-path', '/tmp/tmppei1qeps']
[2025-04-22T20:09:04.227+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask upload_to_hdfs
[2025-04-22T20:09:04.257+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_kafka_pipeline.upload_to_hdfs scheduled__2025-04-22T19:50:00+00:00 [running]> on host b667aa68beae
[2025-04-22T20:09:04.320+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_kafka_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T19:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T19:50:00+00:00'
[2025-04-22T20:09:04.320+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-22T20:09:04.336+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T20:09:04.336+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c " dfs -put -f /opt/airflow/includes/local\\ warehouse/bronze/stock-prices.jsonl hdfs://localhost:9000/bronze/"']
[2025-04-22T20:09:04.347+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T20:09:04.351+0000] {subprocess.py:93} INFO - bash: line 1: dfs: command not found
[2025-04-22T20:09:04.352+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-04-22T20:09:04.352+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-22T20:09:04.359+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-22T20:09:04.362+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stock_kafka_pipeline, task_id=upload_to_hdfs, run_id=scheduled__2025-04-22T19:50:00+00:00, execution_date=20250422T195000, start_date=20250422T200904, end_date=20250422T200904
[2025-04-22T20:09:04.374+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 130 for task upload_to_hdfs (Bash command failed. The command returned a non-zero exit code 127.; 119)
[2025-04-22T20:09:04.398+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-22T20:09:04.409+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T20:09:04.410+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
